- README.md
I added the "-L" switch to curl. 
> fixed readme downloading information (curl needs -L to follow redirect)

- kleinanzeigen_bot/__init__.py
63
Sort images on a per path/pattern basis instead of sorting all of them at once after reading them. Also using list instead of set since it is ordered.
Changes are not tested, as I did not manage to get the app installed and running from source.
> Sort images per path (needs testing)

- kleinanzeigen_bot/__init__.py
- kleinanzeigen_bot/utils.py
*Issue #, if available:* https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/125
- CHANGE When downloading an ad, save the created_on value as string (not datetime) to the ad yaml in accordance to how the updated_on value is saved by the (re-)publish function
- ADD parse_datetime helper function
- UPDATE Parsing of created_on/updated_on so it does allow datetime values in the ad yaml
> CHANGE Save created_on date as string to ad yaml

- kleinanzeigen_bot/extract.py
*Issue #, if available:* https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/127
- FIX Save person name as contact:name to ad yaml instead of city name
The `download` action saved the city name to the contact:name variable in the ad config file, but it should be the person name. This pull request fixes the behavior and saves the person name to the variable correctly.
This PR is ready to be merged.
> FIX when downloading save person name as contact name; not the city

- kleinanzeigen_bot/__init__.py
Sometimes it takes longer until the confirmation is shown, that the classified ad is published. In that case the pause aborts the publish process. To avoid this, changed to wait for a confirmation been visible.
> Wait for confirmation page

- README.md
- kleinanzeigen_bot/__init__.py
- kleinanzeigen_bot/extract.py
- kleinanzeigen_bot/utils.py
*Implement #131 *
Supply the `--all` flag to download all of the ads on your profile. The feature browses and scrolls the ad section on your profile. It supports multiple ad overview pages, if you have more than 25 ads. This has been tested with 0-50 ads. The references to your ads are captured, and the 'download ad' feature used on them.
> ADD download --all feature

- README.md
- kleinanzeigen_bot/__init__.py
- kleinanzeigen_bot/extract.py
- kleinanzeigen_bot/resources/ad_fields.yaml
- kleinanzeigen_bot/resources/config_defaults.yaml
*Issue #, if available:* none
*To be discussed*
> ADD ability to select shipping packages and sell directly

- README.md
- kleinanzeigen_bot/__init__.py
- kleinanzeigen_bot/extract.py
- kleinanzeigen_bot/resources/config_defaults.yaml
#149 #136 
- To mitigate crashing when scanning the ad overview page, the selection of the `<section>` element is now more robust, and now should not depend on dynamic class assignment.
- Configured the standard ads path as suggested by @baflo. The downloaded ads are assigned to a specific directory. 
- Slightly adjusted load_ads, with a new optional parameter, and explicitly skipping _ad_fields.yaml_. Even if the ads selector is 'new', setting the second optional parameter to false allows to load all ads, if needed.
> Fix download element and path problems

- kleinanzeigen_bot/__init__.py
pstad-price is not always visible, click on pstadt-description instead
Publishing crashed when trying to click on pstad-price element. For some reason the element was not visible for me, but some other price field was.
I changed the field to be clicked to the description box because it is always visible.
> FIX do not click on pstad-price to wait for category detection

- .gitignore
Gitignore the hardcoded `downloaded-ads` folder which will be created and used to save the downloaded ads in.
> ADD .gitignore downloaded-ads folder

- kleinanzeigen_bot/__init__.py
Sell directly was not handled correctly.
Issue:  #155
Description of changes: Now sell directly is analyzed if is already been clicked. Compared with wished configuration. If it's not visible is handled via exception handling.
> Fixed #155 sell directly

- kleinanzeigen_bot/__init__.py
Checking if a user is already logged in skips redundant logins and improves automation regarding to many captchas. This is vital when using user_data_dir for storing session tokens.
> Now the program checks if the user is already logged in

- src/kleinanzeigen_bot/extract.py
This fixes the following issue:
```
$ ./kleinanzeigen-bot --ads=all download
[...]
[INFO]  ... pausing for 1995 ms ...
[INFO] New directory for ad created at downloaded-ads/ad_2682902075.
[INFO] Extracting information from ad with title "Bandauflösung Tonstudio mit Rack, Faderport, Audio-PC, Funkmikros"
[ERROR] ValueError: invalid literal for int() with base 10: '4.500'
[2025675] Failed to execute script '__main__' due to unhandled exception!
successfully removed temp profile /tmp/uc_l5mu72fo
```
> Fix: Crash on downloading ads with prices >=1000 Eur

- src/kleinanzeigen_bot/extract.py
https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/283
changed the id name
> fix: No HTML element found with ID 'my-manageads-adlist'

- src/kleinanzeigen_bot/extract.py
pdm run app download --ads=2xxxxx will result in crash because page is still None, navigating to startpage fixes this.
> Fix download on given IDs list

- src/kleinanzeigen_bot/extract.py
#278
The button selector for the navigation button has changed. This PR fixes the selector, so downloading ads when having multiple pages will work again.
> fix navigation button selector

- src/kleinanzeigen_bot/extract.py
*Issue #, if available:* no issue
*Description of changes:* Web element with id `j-buy-now` does not exist anymore. Fetch the `payment-buttons-sidebar` instead and check the text for `Direkt kaufen`
> FIX extract sell directly from ad page

- src/kleinanzeigen_bot/__init__.py
*Issue #, if available:* fixes #292
*Description of changes:* Depending on the input, one shipping size and all their options are preselected. If we want to keep that shipping size, we have to click (unselect) the unwanted options instead
Furthermore the PR fixes the wrong shipping size of DHL_10.
Code inspired by @bochen87
> FIX selection of shipping options

- src/kleinanzeigen_bot/extract.py
https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/312
kleinanzeigen returns a non valid JSON string for the special_attributes. I converted the string to a valid JSON object.
> fix: special attributes cannot be parsed as JSON #312

- src/kleinanzeigen_bot/extract.py
Format of special attribute changed to "key:value|key:value" instead of "key:value,key:value".
*Issue #, if available:* #318
Instead of transforming the string to JSON, directly create a dictionary from belen_conf from the changed format
Credits @dbcesar https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/318#issuecomment-2225804554
> FIX extract special attributes from ad page

- src/kleinanzeigen_bot/__init__.py
fixes #281
*Description of changes:* 
This Pull Requests submits two fixes.
1) The condition is nowadays set within a dialog. I added a function to set the condition accordingly. My implemented option is backwards compatible and requires a mapping from the condition_s key to the friendly name which shall be selected. It might be an idea to change the download behavior to save the condition friendly name ("Neu" instead of the condition_s key "new") in another issue?
2) The special attributes field keys changed from "key" to "category.key". We currently haven't saved the category name anywhere, which makes it difficult to select the special attribute field by full name. Instead this hotfix uses "contains" to find the special attributes field. Credits @Vel-San …
> Fix selection of special attributes

- src/kleinanzeigen_bot/extract.py
*Issue https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/323
At issue https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/323 the ad_2827968602 had NO special_attributes.  This broke down the for loop.
-> Fixed by adding a check for items.
@sebthom: Kindly review and merge the PR
> fix: ValueError when downloading ads without special_attributes

- src/kleinanzeigen_bot/__init__.py
> Fix for error #353 and #351

- src/kleinanzeigen_bot/__init__.py
The login check can fail unnecessary when the username does not match case sensitive.
Make the check case insensitive by lowering both strings.
> FIX login check has to be done case insensitive

- src/kleinanzeigen_bot/__init__.py
- src/kleinanzeigen_bot/extract.py
Refactored setting of specail attributes. This still has some effects in some cases since special attribute can have dependencies on each other and must be in an special order. For example in category car, the special attribute 'marke_s' must be set before 'model_s', otherwise when setting 'marke_s' 'model_s' gets cleared.
> fix: failed to set special attributes #334

- README.md
- src/kleinanzeigen_bot/__init__.py
- src/kleinanzeigen_bot/extract.py
#375
Refactored extraction of shipping options to use options directly from kleinanazeigen. 
Add new option DHL_20 for packets up to 20kg.
> fix shipping options when downloading 

- src/kleinanzeigen_bot/__init__.py
When multiple cities are available for a ZIP code, the bot now correctly selects the city specified in the YAML file's `location` field instead of always choosing the first option.
- Adds logic to select the correct city from the dropdown based on the `location` field.  
- Adds a small delay after ZIP code input to allow the dropdown to populate.  
- Uses the proper `WebScrapingMixin` method to read dropdown options.  
_None_
Fixes a bug in city selection when multiple locations are available for a postal code. Previously, the first location was always selected, even if a different one was specified in the YAML file.
1. Create a listing with a postal code that has multiple location options (e.g., `27321`).  
2. In the YAML file under `contact`, specify both the `zipcode` and a `location`: …
> fix: correct city selection when multiple cities are available for a ZIP code

- src/kleinanzeigen_bot/utils.py
- tests/test_utils.py
This PR fixes a TypeError that occurs when ad configurations contain None values.
- Link to the related issue(s): Issue #395
- The issue occurs with ad configurations that don't have a content_hash yet and contain None values.
- Added test case to reproduce TypeError with None values
- Improved handling of None values in `calculate_content_hash`:
- `special_attributes`: None becomes empty dictionary
- `shipping_options`: None becomes empty list
- `images`: None values in list become empty strings
- Consistent handling of empty values (empty string instead of "None")
I confirm that this contribution can be used, modified, copied, and redistributed under the terms of the project license.
> fix: Handle None values in calculate_content_hash (#395)

- pdm.lock
- pyproject.toml
- tests/conftest.py
- tests/unit/test_extract.py
This PR adds a comprehensive test suite for `extract.py` to improve test coverage and ensure proper functionality of the ad extraction features.
- Link to the related issue(s): #399
- Motivation: Improve test coverage and code reliability by adding comprehensive tests for the ad extraction functionality.
- Added complete test suite for `extract.py` with the following test classes:
- `TestAdExtractorBasics`: Tests for constructor and URL parsing
- `TestAdExtractorPricing`: Tests for price extraction and formats
- `TestAdExtractorShipping`: Tests for shipping information and DHL options
- `TestAdExtractorNavigation`: Tests for page navigation and popup handling
- `TestAdExtractorCategory`: Tests for category extraction
- `TestAdExtractorContact`: Tests for contact information extraction
- …
> test: Add comprehensive test suite for extract.py

- src/kleinanzeigen_bot/__init__.py
This pull request addresses an issue with the content hash calculation in the `KleinanzeigenBot` class. The content hash was previously calculated on the current configuration, which could lead to inconsistencies. This change ensures that the hash is calculated on the original configuration, improving the reliability of the ad republishing process.
- Link to the related issue(s): Issue #413
- The motivation for this change is to ensure consistent behavior when checking for changes in ad configurations and to maintain the integrity of the content hash across sessions.
- Updated the `__check_ad_republication` method to calculate the content hash on the original configuration (`ad_cfg_orig`) instead of the current configuration (`ad_cfg`).
- Modified the `publish_ad` method to calculate the …
> fix: Ensure Consistent Content Hash Calculation

- src/kleinanzeigen_bot/__init__.py
This PR fixes the KeyError: 'description' issue reported in #432 by properly handling description affixes in a single method.
- Link to the related issue(s): Issue #432
- The issue occurred because description prefix/suffix handling was inconsistent across the codebase. This PR consolidates all description text processing into the `__get_description_with_affixes` method.
- Moved `@` -> `(at)` replacement into `__get_description_with_affixes` method
- Removed duplicate prefix/suffix handling code
- Ensures consistent description text processing in one place
> fix: consolidate description text processing (#432)

- pyproject.toml
- src/kleinanzeigen_bot/__init__.py
- tests/unit/test_init.py
This PR makes the description field in the main configuration (`ad_defaults`) optional, addressing issue #435. Previously, the bot would fail if no description or affixes were provided in the main configuration. This change improves flexibility for users while maintaining backward compatibility.
- Link to the related issue(s): Issue #435
- Motivation: Users should be able to run the bot without requiring description fields in the main configuration, as these can be specified at the individual ad level.
- Add fallback to empty string ("") when all description prefix/suffix sources are None in `__get_description_with_affixes` method
- Add comprehensive test suite for description handling in `test_init.py`
- Fix coverage path in `pyproject.toml` from 'kleinanzeigen_bot' to …
> fix: Make description field optional in ad_defaults (#435)

- README.md
- src/kleinanzeigen_bot/__init__.py
- src/kleinanzeigen_bot/resources/translations.de.yaml
- tests/unit/test_init.py
This PR fixes a bug where the 'due' selector was also publishing changed ads regardless of their age. It implements a new 'changed' selector for the `--ads` option and ensures that the 'due' selector only republishes ads based on the time interval.
- Link to the related issue: Issue #411
- The motivation for this change is to provide users with more control over which ads are republished, allowing them to specifically target changed ads or due ads, or combine both behaviors.
- Added a new 'changed' selector for the `--ads` option that publishes only ads that have been modified since their last publication
- Modified the 'due' selector to only republish ads based on the time interval, without considering content changes
- Refactored the ad republication logic by splitting it into two …
> fix: Add 'changed' selector and separate it from 'due' selector behavior

- src/kleinanzeigen_bot/__init__.py
- src/kleinanzeigen_bot/resources/translations.de.yaml
The PR fixes setting of custom shipping price, where no shipping options were given.
- Link to the related issue(s): Issue #448
- The motivation is the correct handling of this case.
- check if shipping costs are set when no other options are set and then put them into right place
- [x ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [x ] I have reviewed my changes to ensure they meet the project's standards.
- [x ] I have tested my changes and ensured that all tests pass  (`pdm run test`).
- [x ] I have verified that linting passes (`pdm run lint`).
- [x ] I have run security scans and addressed any identified issues (`pdm run audit`).
- [x ] I have updated …
> fix: set custom shipping due css update #448

- src/kleinanzeigen_bot/__init__.py
This PR fixes the shipping costs logic when using zero or none shipping costs and no shipping options are set.
- Link to the related issue(s): Issue #458
- shipping_costs with value 0 lead to use 0,00EUR Versandkosten
- empty shipping_costs lead to default value (three shippers), when no shipping options are selected
- [ x] 🐞 Bug fix (non-breaking change which fixes an issue)
> fix: setting zero shipping costs

- src/kleinanzeigen_bot/extract.py
Element button was changed to em.
Changing element button to 'em'
- Link to the related issue(s): Issue #475
- now searching for element 'em' to find pagination
- [ x] 🐞 Bug fix (non-breaking change which fixes an issue)
> fix: CSS selector 'button' not found

- src/kleinanzeigen_bot/__init__.py
Instead of using XPATH to identify the custom shipping checkbox now using the id of this input.
- Link to the related issue(s): Issue #474 
- Describe the motivation and context for this change.
The site changed structure and the xpath selectors were outdated. This caused the click for the custom shipping checkbox was wrong.
Bullet-point key changes introduced.
- changed click method from XPATh to ID with the propper id of the input element
> fix: correct setting custom shipping costs

- README.md
- src/kleinanzeigen_bot/__init__.py
- src/kleinanzeigen_bot/__main__.py
- src/kleinanzeigen_bot/resources/translations.de.yaml
- src/kleinanzeigen_bot/utils/exceptions.py
- src/kleinanzeigen_bot/utils/loggers.py
- tests/unit/test_i18n.py
Adds an **automatic restart loop after a captcha is encountered**.  
Instead of waiting for manual confirmation, the bot now
1. aborts the current run as soon as a captcha appears,
2. sleeps for the duration defined in `captcha.restart_delay_h` (default 6 h),
3. starts a fresh run automatically.
This allows continuous publishing of up to 10 ads, then a cooldown, then another 10, … without user interaction.
*Related issue:* #<issue-number>
- **`src/kleinanzeigen_bot/__main__.py`**  
* new while-loop wrapper that catches `CaptchaEncountered`, sleeps, and restarts  
* YAML helper to read `captcha.restart_delay_h` from config
- **`src/kleinanzeigen_bot/__init__.py`**  
* (optional) added `shutdown()` coroutine for graceful browser / WebSocket cleanup
- …
> feat: captcha auto-restart

- src/kleinanzeigen_bot/extract.py
- src/kleinanzeigen_bot/resources/config_defaults.yaml
- tests/unit/test_extract.py
Add functionality to include all shipping options of the same package size when `include_all_matching_shipping_options` is enabled
This PR adds functionality to store all shipping options of the same package size when downloading ads, instead of just the one matching the exact price. This is useful when multiple shipping options are available for the same package size (e.g., DHL and Hermes options for small packages). 
Additionally, it allows excluding specific shipping options (e.g., when certain carriers are not available in a region).
- Link to the related issue(s): N/A
- The motivation for this change is to provide more flexibility in shipping options when downloading ads, allowing users to:
- See all available shipping options for a given package size rather than just the one …
> feat: add support for multiple matching shipping options

- src/kleinanzeigen_bot/__init__.py
- tests/unit/test_extract.py
- tests/unit/test_init.py
The login detection has been improved by adding a fallback element. This increases the reliability of login detection as two different elements are now checked. If the primary element (`mr-medium`) is not found, an alternative element (`user-email`) is checked.
- Link to the related issue(s): N/A
- Implementation of a fallback check for the `user-email` element when `mr-medium` is not found
- Improvement of login detection reliability through redundant checking
- Addition of a test case for the alternative login element
- No additional dependencies or configuration changes required
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
> fix: improve login detection with fallback element

- src/kleinanzeigen_bot/__init__.py
- src/kleinanzeigen_bot/extract.py
- src/kleinanzeigen_bot/resources/translations.de.yaml
- tests/unit/test_extract.py
The form input elements on the main page have been refactored, so the bot couldn't find them. 
- Link to the related issue(s): Issue #508
- Downloading an single ad with given id should be possible.
- Instead of filling the search form, the bot now submit the data directly to the search.
- Renamed function naviagte_to_ad_page to navigate_to_ad_page
> fix: Unable to download single ad

- src/kleinanzeigen_bot/__init__.py
Before the password in the login funtion is send, now an empty string is send to clear an preassigned value from the browser passwordmanager.
- Link to the related issue(s): Issue #530 
- fill_login_data_and_send now send an empty string before the password
> fix: clearing password input while logging in

- src/kleinanzeigen_bot/__init__.py
- src/kleinanzeigen_bot/extract.py
- tests/unit/test_extract.py
This PR fixes the handling of special attribute "art_s". Generally "art_s" is used for the subcategory, but sometimes it becomes the meaning of an special attribute.  So now the subcategory is taken from the BelenConf dictionary and "art_s" entry dont gets deleted anymore.
Actually the subcategory isn't really necessary, but when given, the appropriate special attribute gets preselected. 
- Link to the related issue(s): Issue #434 
- take subcategory from BelenConf
- removed deletion of "art_s" entry
- fixed condition translation table
> fix: setting special attribute when key is art_s

- src/kleinanzeigen_bot/extract.py
I got an error because the key dimension92 wasn't defined on one of my posts.
do not throw an KeyError when dimension92 is missing
> fix: dimension92 may not be defined in universalAnalyticsOpts

- src/kleinanzeigen_bot/resources/translations.de.yaml
- src/kleinanzeigen_bot/update_checker.py
- tests/unit/test_update_checker.py
This PR improves the update check logic and log clarity in the update_checker module, and ensures translation completeness for new log messages.
- Link to the related issue(s): _N/A_
- Motivation: The update checker previously logged a misleading message when the local and release commit hashes were identical. Additionally, log timestamps did not explicitly indicate UTC, and translation checks failed due to outdated message keys.
- Fix update check logic: Only log "You are on the latest version" when local and release commit hashes are identical, and return early to avoid misleading logs.
- Add " UTC" to all commit timestamps in update_checker log messages for clarity.
- Update unit tests to expect new log message formats with UTC.
- Update German translations for update_checker log …
> fix: improve update check logic and UTC log clarity

- src/kleinanzeigen_bot/extract.py
- tests/unit/test_extract.py
Due changes in site layout the page ref selector has changed. This PR refactors the selector to adapt the changes.
- Link to the related issue(s): Issue #592
- refactored CSS selector for ad references
> fix: refactored page ref selector
