Second-Hand-Friends/kleinanzeigen-bot

README.md
kleinanzeigen_bot/resources/categories.yaml
kleinanzeigen_bot/resources/config_defaults.yaml

Fixes #21. Additionally, correct cat. notebooks

add example for 3rd-level category conf

---

kleinanzeigen_bot/resources/config_defaults.yaml

typo fixed

---

kleinanzeigen_bot/resources/categories.yaml

The category ids for women's shoes were wrong, probably a typo (the previous ids were the ones for men's shoes which are very similar). Fixed them in this PR.

fix: fixed category ids for women's shoes

---

kleinanzeigen_bot/resources/categories.yaml

Added Reifen to categories
*Description of changes: Added "Reifen" as category

Updated categories.yaml

---

kleinanzeigen_bot/__init__.py

#74 
added a check if the street field is enabled before trying to fill the input field 

check if street input is enabled

---

kleinanzeigen_bot/__init__.py

#74 #75 
added a setting for address visibility and set the checkmark accordingly to enable the street input field

set address visibility field per setting

---

kleinanzeigen_bot/__init__.py

*Issue:* #80
I copied and pasted the code from the "Adress Visibility fix" #79 to make sure the phoneNumberVisibility checkbox is clicked.

Added compatibility with phoneNumberVisibility checkbox.

---

kleinanzeigen_bot/__init__.py

Issue #99
Trying to fix sometimes not existing radio button click for shipping options. 

Attempt fixing #99

---

kleinanzeigen_bot/__init__.py

*Issue #106*
Code proceeds as usual but if selecting 'old' Ids result in raise of exception it tries *new* ids

Updating to changes with PriceType and Price. Fixes #106

---

kleinanzeigen_bot/resources/categories.yaml

Adds missing Elektronik categories.
No existing key names were edited to remain compatible with existing ads.

Adds missing Elektronik categories

---

kleinanzeigen_bot/__init__.py
kleinanzeigen_bot/extract.py

*Fix 3 minor bugs*
- create base download directory, if not exists
- pick correct image gallery symbol in case 'Virtueller Rundgang'
- select name correctly when no link given

Minor fixes

---

kleinanzeigen_bot/extract.py

*Issue #, if available:* https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/126
Fix downloading of special attributes and fetch the correct keys and values from the `window.BelenConf` javascript variable in the page source of an ad page.
Ready to be merged. Feel free to squash the PR.

Resolve #126 download special attributes

---

kleinanzeigen_bot/__init__.py

Old repo URL has 404 error.
Updated to recen URL

Update of repo RUL in init.py. Old URL has 404 error.

---

kleinanzeigen_bot/__init__.py

#45 
Try 3 times to upload an image. This solves about 90% of all aborted ads for me.

Improve image upload handling

---

kleinanzeigen_bot/resources/categories.yaml

Adding catories of "Haus & Garten > Wohnzimmer"

Add categories for Wohnzimmer

---

kleinanzeigen_bot/__init__.py

Fixes #217, #214, #200, #195
Likely #216, #196
And some issue about custom shipping costs I can't find anymore

Various fixes

---

kleinanzeigen_bot/__init__.py

Fixes #220

---

kleinanzeigen_bot/__init__.py

#233 Check first for shipping type.

Fixed no element error when shipping type is pickup.

---

kleinanzeigen_bot/__init__.py

#238 Fixes the shipping handling

fixed wrong shipping options handling

---

src/kleinanzeigen_bot/extract.py

Fix VB Price with thousand separator

---

src/kleinanzeigen_bot/extract.py

Fixes https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/282
- Selector is now done by class, not ID
- Updated prices

fix: download of shipping info. Fixes #282

---

README.md

Seems like some code has been moved to sub directory `src`. Fixing README link in comment.

Fixing missing src directory in README

---

src/kleinanzeigen_bot/__init__.py

*Issue #, if available:* fixes #301
*Description of changes:* wait for user interaction to solve captcha on publishing ad

UPDATE wait for user interaction to solve captcha on publishing ad

---

src/kleinanzeigen_bot/web_scraping_mixin.py

*Issue #, if available:* fixes #276, fixes #300
*Description of changes:* selecting the wanted index doesn't trigger a change event which is necessary to update  internal variables regarding the price type
related https://stackoverflow.com/a/60661665

FIX selecting price type

---

src/kleinanzeigen_bot/web_scraping_mixin.py

no 
chrome displays a new search engine popup. This parameter suppresses the popup

Disable search engine popup with chrome

---

src/kleinanzeigen_bot/__init__.py

Issue https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/339
- Do a double login if it is required
*Details*
- Somehow the double login is not required anymore so i cannot test it at the moment

fix: double login required

---

src/kleinanzeigen_bot/__init__.py
src/kleinanzeigen_bot/resources/translations.de.yaml

#365 
Before publishing now check if ad has state "paused" and then skip this ad

feat: dont republish reserved ads

---

src/kleinanzeigen_bot/__init__.py

#367
calss was renamed. Now getting button per aria-label attribute should be more robust.

fix setting shipping options #367

---

src/kleinanzeigen_bot/__init__.py

#371
added detection of image-question

fix re-publishing without images #371

---

src/kleinanzeigen_bot/__init__.py

#367
Button with label occurs often. Path must be corrected.

path to button must be precised

---

src/kleinanzeigen_bot/__init__.py

#385 
searching for now subclass `SelectionButton`

fixed shipping button class

---

README.md
pyproject.toml
src/kleinanzeigen_bot/__init__.py
src/kleinanzeigen_bot/extract.py
src/kleinanzeigen_bot/resources/translations.de.yaml
src/kleinanzeigen_bot/utils.py

This PR enhances hash-based change detection for ads.
- Implement hash-based change detection as the default behavior
- Improve consistency in hash calculation:
- Apply consistent type conversion for all fields
- Treat image paths as filenames
- Handle `None` values as the string "None"
- Add German log messages
- Update documentation in the README
- Downloading ads
- Publishing new ads
- Detecting changes in existing ads
- Republishing modified ads
Fixes #343

Improve Hash-Based Change Detection (#343)

---

src/kleinanzeigen_bot/__init__.py

Display num of chars in description if 4000 chars are exceeded.
Fixes #402 

Display num of chars in description

---

pdm.lock
pyproject.toml
tests/conftest.py
tests/unit/test_extract.py
tests/unit/test_init.py

This PR significantly enhances the test coverage of the KleinanzeigenBot class by adding comprehensive test suites in test_init.py. The changes introduce structured test organization, reusable fixtures, and thorough testing of core functionalities.
- Link to the related issue(s): none
- The changes focus on improving test coverage and maintainability while ensuring proper type checking and development tooling.
- Added test classes for distinct functionality areas:
- `TestKleinanzeigenBotInitialization`
- `TestKleinanzeigenBotLogging`
- `TestKleinanzeigenBotCommandLine`
- `TestKleinanzeigenBotAuthentication`
- `TestKleinanzeigenBotLocalization`
- `TestKleinanzeigenBotBasics`
- `TestKleinanzeigenBotArgParsing`
- `TestKleinanzeigenBotCommands`
- `TestKleinanzeigenBotAdOperations`
- …

test: Enhance test coverage for KleinanzeigenBot initialization and core functionality

---

src/kleinanzeigen_bot/extract.py

fixing download all ads #420

---

src/kleinanzeigen_bot/__init__.py

After publishing checking for delay message and confirm it.

fixes publishing delayed ad #414

---

src/kleinanzeigen_bot/__init__.py
src/kleinanzeigen_bot/resources/translations.de.yaml

- Link to the related issue(s): Issue [#440](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/440)
- Describe the motivation and context for this change.
updated the class selectors
- [x ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [x ] I have reviewed my changes to ensure they meet the project's standards.
- [x ] I have tested my changes and ensured that all tests pass  (`pdm run test`).
- [x ] I have verified that linting passes (`pdm run lint`).
- [x ] I have run security scans and addressed any identified issues (`pdm run audit`).
- [x ] I have updated documentation where necessary.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …

fix: Update css class selectors fixing #440 

---

src/kleinanzeigen_bot/resources/translations.de.yaml
tests/unit/test_translations.py

This PR cleans up the German translation file by removing obsolete entries and improves the translation testing infrastructure to better detect unused translations.
- Link to the related issue(s): N/A
- This change helps maintain a cleaner translation file by removing unused entries and preventing future accumulation of obsolete translations through improved testing.
- Removed unused translation entries from translations.de.yaml
- Added KNOWN_NEEDED_MODULES constant to handle special cases in translation testing
- Implemented new _message_exists_in_code helper function for better translation verification
- Improved test failure messages to show both original and translated text
- Enhanced translation verification logic
- Fixed import sorting in test file
Before requesting a review, …

fix: Remove obsolete German translations and improve translation testing

---

src/kleinanzeigen_bot/__init__.py

This PR adds support for the condition "Defekt".
- Link to the related issue(s): Issue #460
- added condition defect to the bot.

enh: Adding condition "Defekt"

---

src/kleinanzeigen_bot/__init__.py

Fix logon detection and double suffix
Fixes #484 #485 #487 
Fixes #484 #485 #487 

fix: logon detection and duplicate suffix in ad description

---

src/kleinanzeigen_bot/__init__.py

fix: Unable to close shipping dialog

---

src/kleinanzeigen_bot/__init__.py

This PR fixes the deselection of unwanted shipping options.
- Link to the related issue(s): Issue #522 
- corrected XPATH expression for deselection of shipping options

fix: Setting shipping options correctly

---

pdm.lock
src/kleinanzeigen_bot/__init__.py
src/kleinanzeigen_bot/resources/translations.de.yaml
tests/unit/test_init.py

This PR adapt the changed ids from the login input elements. Also the handling of the captcha is centralized in one function.
- Link to the related issue(s): Issue #539 
- refactored input element ids
- refactored captcha detection and handling in one function

fix: login form handling

---

src/kleinanzeigen_bot/__init__.py

Refactored set_condition function to adapt changes in condition dialog structure.
- Link to the related issue(s): Issue #547 
- refactored identifier of condition dialog open button 
- refactored identifier of condition dialog accept button

fix: refactored setting condition

---

src/kleinanzeigen_bot/__init__.py

Due minor ui changes setting of shipping options fails and article condition fails.
This PR fixes the corresponding xpath expressions and adds an extra condition mapping.
- Link to the related issue(s): Issue #567 
- refactored xpath expressions
- added new internal condition for value "Gut"

fix: Refactored some xpath expressions

---

src/kleinanzeigen_bot/__init__.py
tests/unit/test_init.py

Due changes in site layout the shipping size selectors have changed. This PR refactors the selectors to adapt the changes.
- Link to the related issue(s): Issue #580 
- refactored shipping size option selector

fix: refactored setting shipping size

---

src/kleinanzeigen_bot/__init__.py

This PR add the functionality to set individual shipping without providing shipping costs.
- Link to the related issue(s): Issue #622
- refactored set_shipping logic

feat: Allow individual shipping without setting shipping costs
